[package]
name = "bochscpu"
version = "0.1.0"
authors = ["x"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
ctor = "0.1"
lazy_static = "1"
log = "0.4"

[build-dependencies]
cc = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
